import * as pty from 'node-pty'
import { EventEmitter } from 'node:events'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { LaunchSpec } from './adapters.js'
import { DATA_DIR } from './store.js'

/**
 * Scrollback kept per session so a node can be drawn as a preview, evicted, and later re-mounted
 * as a full terminal without losing what happened. This is the same byte stream in every case,
 * which is why a preview is never a mirror or a reconstruction.
 */
const SCROLLBACK_LIMIT = 256 * 1024

/**
 * How far past the limit a buffer may run before it is trimmed back to it.
 *
 * The trim used to happen on every chunk the moment the buffer was full, and a chunk is what a CLI
 * emits several hundred times a second while it is drawing. Each one meant slicing a quarter of a
 * megabyte of string, on the same thread that reads every PTY and serves every socket, so the
 * busier the board got the slower it got at exactly the wrong moment. Letting the buffer run half
 * again over the limit turns that into one slice per 128 KB printed, and costs at most 128 KB of
 * extra memory per live card.
 *
 * Measured, because the rest of this hunt turned up two theories that looked expensive on paper and
 * cost nothing in practice. Twenty thousand chunks appended to a full buffer: 1744 ms of blocking
 * before, 8 ms after. That is the one number in the set that was worth the change.
 *
 * The limit itself is unchanged: what a client is ever handed is still trimmed to it.
 */
const SCROLLBACK_SLACK = SCROLLBACK_LIMIT / 2

/**
 * How much of the tail the token reader is given.
 *
 * It looks for the figures the CLI prints on its spinner line and in its agent tree, both of which
 * are drawn at the bottom of the screen, so the top of a 256 KB buffer cannot contain an answer it
 * does not already have from lower down. It was handed the whole buffer once a second per live
 * session regardless.
 *
 * Not a fix for anything, and worth saying so. Measured, `readTokens` over a full 256 KB buffer
 * takes about 0.10 ms, so ten live cards cost roughly one millisecond a second, and over the tail
 * about 0.08 ms. It looked like the expensive loop and it is not. This stays because reading only
 * what can hold the answer is the right shape, not because it bought back any time.
 */
const TOKEN_TAIL_BYTES = 32 * 1024

/**
 * The grid a session is spawned with, named rather than left as defaults on one function.
 *
 * Two other places need this exact pair: the scrollback reply, which has to tell a client what
 * geometry the bytes were drawn against, and the card preview, which builds its own emulator to
 * interpret them. When it was an inline default on `spawn` only, the preview picked its own numbers
 * and nothing ever noticed they disagreed.
 */
const SPAWN_COLS = 120
const SPAWN_ROWS = 30

/**
 * The same scrollback, kept on disk so it outlives the process that printed it.
 *
 * In memory it lived in the `live` map and was deleted the moment the PTY exited, so a stopped
 * card said "no output yet" and a server restart wiped every card's terminal at once, while the
 * card row, its role and its wires all came back from SQLite. The board remembered everything
 * except the one thing the owner was reading.
 *
 * These files are a plain byte-for-byte copy of what the process printed, capped at the same
 * SCROLLBACK_LIMIT as the memory buffer so a long-running card cannot grow one without bound.
 * Nothing here is summarised or reconstructed, and restoring one never starts, restarts or
 * otherwise touches a process: reading a file is the whole of it, and a stopped card stays
 * stopped with its status still coming from the session row.
 */
function scrollbackDir(): string {
  const dir = join(DATA_DIR, 'scrollback')
  mkdirSync(dir, { recursive: true })
  return dir
}

/**
 * The buffer as anyone outside this module is allowed to see it.
 *
 * The in-memory buffer is now allowed to run over the limit between trims, so every way out of here
 * goes through this rather than each caller remembering to cut it. Without it the slack would have
 * quietly become the new limit for both the client snapshot and the file on disk.
 */
function capped(buffer: string): string {
  return buffer.length > SCROLLBACK_LIMIT ? buffer.slice(buffer.length - SCROLLBACK_LIMIT) : buffer
}

function scrollbackPath(sessionId: string): string {
  // Session ids are generated by Garden, but a path separator arriving here would write outside
  // the directory, so the name is reduced to characters that cannot leave it.
  const safe = sessionId.replace(/[^a-zA-Z0-9._-]/g, '_')
  return join(scrollbackDir(), `${safe}.log`)
}

/**
 * The grid the bytes in the log beside this file were drawn against.
 *
 * Kept because the bytes are meaningless without it and the log alone cannot carry it. A CLI does
 * not print finished text; it prints instructions computed for a grid it believes it has, so
 * replaying them at another width puts every wrap somewhere else and every "move up two rows and
 * rewrite" over a line it was never aimed at. The result is the owner's own words for it: columns
 * overwriting each other, words erased.
 *
 * Before this, a card with no live process was told its history was 120x30, the size a session is
 * spawned at, on the reasoning that this is what the bytes were produced against. That is false the
 * moment a pane is opened, because opening one fits the terminal to the pane and resizes the
 * process. Measured on his own `eaf83556` log, which the dock had taken to 163 columns: replayed at
 * 163 it is exactly what he typed, and replayed at 120 the tail reads
 * `equires / f / ny / ection / tating` down the left margin with the next line's characters stacked
 * against the right. Every card is stopped after a server restart, so that was every card at once.
 */
function geometryPath(sessionId: string): string {
  const safe = sessionId.replace(/[^a-zA-Z0-9._-]/g, '_')
  return join(scrollbackDir(), `${safe}.size.json`)
}

/**
 * How often a dirty buffer is written out.
 *
 * A chatty CLI emits data in small chunks many times a second, and writing the whole 256 KB
 * buffer on each of those would be a disk thrash for no gain, since nobody reads the file while
 * the session is live. So the write is deferred: a timer sweeps every dirty session on this
 * interval, which bounds the cost to one write per live session per interval however loud it is.
 * Exit and shutdown flush immediately, so the only output ever at risk is the last couple of
 * seconds before the server is killed outright.
 */
const FLUSH_INTERVAL_MS = 3000

interface Live {
  id: string
  proc: pty.IPty
  /** True once Garden killed this on purpose, so the exit reads as stopped rather than failed. */
  intentional: boolean
  buffer: string
  /** Cumulative bytes emitted, used so a terminal attaching late can dedupe against scrollback. */
  seq: number
  cols: number
  rows: number
  /** Set when bytes have arrived that the file on disk does not have yet. */
  dirty: boolean
  /** When anything was last written into this pty, and when that write last carried a return. */
  lastWriteAt?: number
  lastSubmitAt?: number
}

export interface PtyExit {
  sessionId: string
  exitCode: number
  signal?: number
  /** Killing a process yields a non-zero code, so this is how a turn-off is told from a crash. */
  intentional: boolean
}

export class PtyManager extends EventEmitter {
  private live = new Map<string, Live>()
  private flushTimer: NodeJS.Timeout | null = null

  /**
   * Start a process for this card, on the grid the card was last drawn at.
   *
   * The spawn pair is the fallback and not the default, and the difference is the whole of the
   * owner's "resetting the server messes up the cards conversation views, i have to open terminal
   * for the card to be able to read".
   *
   * A card that has ever had a pane open is not a 120-column card. The pane fits the terminal to
   * itself and resizes the process, `resize` records that pair beside the log, and everything the
   * card has printed since is drawn for that width. When the backend restarts, `revive` starts the
   * card again, and starting it here at 120x30 changed the width underneath a history that had been
   * written at 161: the geometry file was reset to the spawn pair while the log beside it still held
   * bytes drawn at the old one, and the card's own miniature, which follows the size the server
   * reports, re-wrapped a 150-column line into 120 and 30. Measured at exactly those numbers by
   * `scripts/test-restart-keeps-a-card-readable.mjs`, which fails on the spawn pair and passes on
   * this. The dock pane was correct throughout, because opening one resizes the process to fit it,
   * which is why his way out was to open a terminal.
   *
   * The recorded pair is a better answer than 120x30 rather than a certain one: the dock may have
   * been laid out differently since. It does not need to be certain. A pane corrects it on open the
   * way it always has, and until then the card is replaying its own bytes at the width they were
   * written for instead of at a width nothing ever drew at.
   *
   * An explicit pair still wins, for a caller that knows the grid it wants.
   */
  spawn(sessionId: string, spec: LaunchSpec, cwd: string, cols?: number, rows?: number): number {
    if (this.live.has(sessionId)) throw new Error(`session already live: ${sessionId}`)

    const known = cols === undefined && rows === undefined ? readGeometry(sessionId) : null
    cols = cols ?? known?.cols ?? SPAWN_COLS
    rows = rows ?? known?.rows ?? SPAWN_ROWS

    const proc = pty.spawn(spec.file, spec.args, {
      name: 'xterm-256color',
      cols,
      rows,
      cwd,
      env: spec.env,
      // ConPTY is the modern Windows backend; winpty is the legacy fallback node-pty ships.
      useConpty: true,
      /*
       * The bundled ConPTY, not the one built into Windows. This is the fix for the smeared,
       * doubled text the owner had been living with.
       *
       * Windows' in-box ConPTY re-emits its whole screen buffer every time it is resized, and
       * Garden resizes a live PTY constantly: opening a second terminal pane resizes the first one,
       * every panel drag resizes every open pane, starting or stopping any session does it. So a
       * screen the program drew once arrived several times, offset, drawn on top of itself. That is
       * microsoft/terminal#4389, open since January 2020 and still on the backlog, and it is worst
       * for a full-screen alternate-buffer TUI, which is exactly what Claude Code is.
       *
       * Measured rather than argued, by `scripts/test-conpty-reflow.mjs`: a fixture that paints its
       * screen exactly once, stamped so every copy is countable, then six resizes. In-box ConPTY put
       * SIX copies into the stream that the program never sent, one per resize. With this flag, zero,
       * across three runs. `IPty.clear()`, which node-pty documents as the way "to avoid ConPTY
       * possibly reprinting the screen", changed nothing: still six.
       *
       * node-pty calls the flag experimental and ships conpty.dll 1.23.2510.08001 with its own
       * OpenConsole.exe, far newer than the in-box one. `GARDEN_CONPTY_DLL=0` goes back to Windows'
       * copy, because an experimental flag on the path every session runs through should have a way
       * out that does not need a code change.
       */
      useConptyDll: process.env.GARDEN_CONPTY_DLL !== '0',
    } as pty.IWindowsPtyForkOptions)

    const entry: Live = {
      id: sessionId,
      proc,
      intentional: false,
      buffer: '',
      seq: 0,
      cols,
      rows,
      dirty: false,
    }
    this.live.set(sessionId, entry)
    /*
     * Stamped at spawn as well as on every resize, because the file outlives the run that wrote it.
     *
     * A new run starts a fresh log, so whatever pair sits beside it has to be the pair THIS process
     * is drawing for, and nothing else may be assumed. It usually now matches what was already
     * there, since the grid above is read from that same file, and it still has to be written: the
     * fallback path spawns at 120x30 for a card with no record, and an explicit pair from a caller
     * agrees with nothing on disk at all. The record is reset by the thing that resets the bytes.
     */
    writeGeometry(sessionId, cols, rows)
    this.startFlushTimer()

    proc.onData((data) => {
      entry.buffer += data
      entry.seq += data.length
      if (entry.buffer.length > SCROLLBACK_LIMIT + SCROLLBACK_SLACK) {
        entry.buffer = entry.buffer.slice(entry.buffer.length - SCROLLBACK_LIMIT)
      }
      entry.dirty = true
      this.emit('data', sessionId, data, entry.seq)
    })

    proc.onExit(({ exitCode, signal }) => {
      const wasIntentional = entry.intentional
      // Last chance: after this the entry is gone, and everything the process printed with it.
      this.flush(entry)
      this.live.delete(sessionId)
      if (this.live.size === 0) this.stopFlushTimer()
      const payload: PtyExit = { sessionId, exitCode, signal, intentional: wasIntentional }
      this.emit('exit', payload)
    })

    return proc.pid
  }

  /**
   * Type into a session, and say whether the keystrokes actually went anywhere.
   *
   * It returned nothing and swallowed everything before. A session that was not in `live` took the
   * optional chain and vanished, so a wake-up written to a card whose process had just ended looked
   * exactly like one that landed, and the sender was told the message was delivered. That is the
   * shape of failure this app exists to refuse, and it was sitting in the one function every
   * delivery goes through.
   *
   * The try/catch matches `resize` and `kill` below, which have always had one. `proc.write` can
   * throw when ConPTY has torn down underneath us, and this is called from a bare `setInterval`
   * callback, where a throw is not a dropped message but an unhandled rejection taking the server
   * with it.
   */
  write(sessionId: string, data: string): boolean {
    const entry = this.live.get(sessionId)
    if (!entry) return false
    try {
      entry.proc.write(data)
      /*
       * When something was last typed, and when it was last submitted.
       *
       * Garden cannot read a raw terminal composer back: the draft lives in the CLI's own screen and
       * nothing publishes it. What Garden does know is everything that went IN, because every
       * keystroke the owner makes in a card reaches the process through this one function. So a
       * write with no carriage return in it means there is probably text sitting unsent, and that is
       * the honest form of the boundary condition canon states: a card whose composer has had
       * keystrokes since its last submit is not restarted.
       *
       * Wrong in the safe direction when it is wrong. A keystroke that the CLI ignored still reads
       * as a draft, so the answer is "wait" for a card that could have been restarted, rather than a
       * restart that throws away something the owner was in the middle of writing.
       */
      const now = Date.now()
      entry.lastWriteAt = now
      if (data.includes('\r') || data.includes('\n')) entry.lastSubmitAt = now
      return true
    } catch {
      // The process went between the lookup and the write. The caller decides what to say about it;
      // there is nothing to repair here.
      return false
    }
  }

  /**
   * Whether this card's composer has had keystrokes since the last submit.
   *
   * True for a card with no live process, because a card that is not running cannot prove its
   * composer is empty and the boundary check has to fail towards waiting. The caller checks for a
   * process first, so in practice that case is already answered.
   */
  composerDirty(sessionId: string): boolean {
    const e = this.live.get(sessionId)
    if (!e) return false
    if (!e.lastWriteAt) return false
    return e.lastWriteAt > (e.lastSubmitAt ?? 0)
  }

  resize(sessionId: string, cols: number, rows: number) {
    const e = this.live.get(sessionId)
    if (!e) return
    if (cols < 1 || rows < 1 || cols > 1000 || rows > 400) return
    /*
     * The syscall first, and the record only if it worked.
     *
     * These two lines used to sit above the call, so a resize that threw left the entry claiming a
     * size ConPTY never received. That pair is what every client is handed by `scrollback()` and
     * what the dock replays its bytes against, so the one number the whole geometry story rests on
     * could be a size nothing had ever been drawn at. This project's rule is not to show the owner
     * something it cannot prove; a size that was refused is exactly that.
     */
    try {
      e.proc.resize(cols, rows)
    } catch {
      // A process that exited between the check and the call is not an error worth surfacing. The
      // recorded geometry stays whatever was last known to have worked.
      return
    }
    e.cols = cols
    e.rows = rows
    /*
     * On disk immediately rather than with the buffer on the flush timer.
     *
     * The two are written at completely different rates and the pairing only has to be right at one
     * moment, which is the one nobody is present for: the process is gone and something asks what
     * its history means. A resize is a handful of events across a session's life, so writing it as
     * it happens costs nothing, and it means the size on disk is never behind the bytes on disk.
     */
    writeGeometry(sessionId, cols, rows)
  }

  /**
   * What this card printed, live buffer first and the file on disk otherwise.
   *
   * This is a read and nothing else. It never spawns, revives or signals anything, so refreshing
   * the app cannot bring a stopped card back up, and the card's status still comes from its
   * session row rather than from the presence of restored bytes.
   *
   * The restored seq is 0 on purpose. The web client dedupes by cumulative byte count: it drops a
   * snapshot whose seq equals what it has drawn, and drops live chunks whose seq is not greater.
   * A live session counts seq up from 0 for the process currently running, so handing back the
   * file's length would sit above the seq of any process started afterwards and the client would
   * silently discard that new output as already seen. Zero cannot do that, because every live
   * chunk carries at least one byte and so is always greater. It also cannot duplicate: a fresh
   * terminal starts at -1 and draws this once, and a second snapshot with the same 0 is
   * recognised as nothing new and skipped.
   */
  /**
   * The buffer, and the geometry it was drawn against.
   *
   * The size travels with the bytes because it is not optional context, it is what the bytes mean.
   * A CLI does not send finished text, it sends drawing instructions computed for the grid it
   * believes it has: wrap here, move up three rows, rewrite. Replay those against a different
   * width and every wrap lands differently, so a "move up three rows" arrives somewhere the CLI
   * never intended and overwrites the wrong line. The card preview was interpreting this stream at
   * 200 by 48 while the process was drawing for 120 by 30, which is why a card showed the right
   * words in the wrong order while the dock terminal, sized to match, was correct.
   *
   * The default for a session with no live process is the size one is spawned at, since that is
   * what the bytes on disk were produced against.
   */
  scrollback(sessionId: string): { data: string; seq: number; cols: number; rows: number } {
    const e = this.live.get(sessionId)
    if (e) return { data: capped(e.buffer), seq: e.seq, cols: e.cols, rows: e.rows }
    /*
     * The size the process was last known to be drawing at, not the size one is spawned at.
     *
     * The spawn constants are still the answer when there is no record, which is honest: a card
     * whose geometry was never written is one that was never resized, so 120x30 is what it ran at.
     * What they are not is an answer for a card the dock had taken to another size, and that is
     * every card the owner has ever opened a pane for.
     */
    const known = readGeometry(sessionId)
    return {
      data: readPersisted(sessionId),
      seq: 0,
      cols: known?.cols ?? SPAWN_COLS,
      rows: known?.rows ?? SPAWN_ROWS,
    }
  }

  /**
   * The last stretch of what a session printed, for readers that only ever look at the bottom.
   *
   * Separate from `scrollback` on purpose. That one is what a terminal is rebuilt from and has to
   * be the whole thing; this one is for the token reader, which runs once a second per live card
   * and was being handed the entire buffer to regex through every time.
   */
  tail(sessionId: string, bytes = TOKEN_TAIL_BYTES): string {
    const e = this.live.get(sessionId)
    if (!e) return ''
    return e.buffer.length > bytes ? e.buffer.slice(e.buffer.length - bytes) : e.buffer
  }

  isLive(sessionId: string): boolean {
    return this.live.has(sessionId)
  }

  kill(sessionId: string) {
    const e = this.live.get(sessionId)
    if (!e) return
    e.intentional = true
    try {
      e.proc.kill()
    } catch {
      // Already gone.
    }
  }

  /**
   * Shutdown. The flush comes first because a clean restart is the common case, and killing the
   * processes and then waiting for their exit events would race the server closing down: the
   * event loop usually stops before onExit ever fires, and every card would lose its history at
   * exactly the moment the owner expects to get it all back.
   */
  killAll() {
    this.flushAll()
    this.stopFlushTimer()
    for (const id of [...this.live.keys()]) this.kill(id)
  }

  private startFlushTimer() {
    if (this.flushTimer) return
    this.flushTimer = setInterval(() => this.flushAll(), FLUSH_INTERVAL_MS)
    // A pending write must never be the reason the server stays alive.
    this.flushTimer.unref?.()
  }

  private stopFlushTimer() {
    if (!this.flushTimer) return
    clearInterval(this.flushTimer)
    this.flushTimer = null
  }

  private flushAll() {
    for (const e of this.live.values()) this.flush(e)
  }

  private flush(e: Live) {
    if (!e.dirty) return
    e.dirty = false
    try {
      writeFileSync(scrollbackPath(e.id), capped(e.buffer), 'utf8')
    } catch {
      // A card whose scrollback cannot be written still works. Losing the record is worth a
      // failed refresh later, not a crashed server now.
    }
  }
}

/** Missing or unreadable means this card has no history, which is a normal state and not an error. */
function readPersisted(sessionId: string): string {
  try {
    return readFileSync(scrollbackPath(sessionId), 'utf8')
  } catch {
    return ''
  }
}

function writeGeometry(sessionId: string, cols: number, rows: number) {
  try {
    writeFileSync(geometryPath(sessionId), JSON.stringify({ cols, rows }), 'utf8')
  } catch {
    // Same reasoning as the buffer flush: a card whose geometry cannot be written still works, and
    // the fallback is the pair it was spawned with rather than nothing.
  }
}

/**
 * Missing means no resize was ever recorded for this card, which the caller reads as the spawn size.
 *
 * Validated rather than trusted, because this is a file on disk that outlives the process and every
 * number in it is handed to a terminal as the truth about what its bytes mean. A junk pair would put
 * a client back in exactly the state this file exists to prevent.
 */
function readGeometry(sessionId: string): { cols: number; rows: number } | null {
  try {
    const raw = JSON.parse(readFileSync(geometryPath(sessionId), 'utf8')) as { cols?: unknown; rows?: unknown }
    const cols = Number(raw.cols)
    const rows = Number(raw.rows)
    if (!Number.isInteger(cols) || !Number.isInteger(rows)) return null
    if (cols < 2 || rows < 2 || cols > 1000 || rows > 400) return null
    return { cols, rows }
  } catch {
    return null
  }
}
